"""initial schema

Revision ID: 539ef484bc80
Revises: 
Create Date: 2026-03-06 23:58:13.325510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539ef484bc80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('master_password_hash', sa.Text(), nullable=False),
    sa.Column('encrypted_user_key', sa.Text(), nullable=False),
    sa.Column('recovery_code_hash', sa.Text(), nullable=False),
    sa.Column('kdf_algorithm', sa.Text(), server_default=sa.text("'argon2id'"), nullable=False),
    sa.Column('kdf_iterations', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('kdf_memory', sa.Integer(), server_default=sa.text('(65536)'), nullable=False),
    sa.Column('kdf_parallelism', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_login', sa.Text(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_authentication_single_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('pinyin_initials', sa.Text(), nullable=False),
    sa.Column('tag_ids', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('urls', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('accounts', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('last_used_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index('idx_bookmarks_last_used', [sa.literal_column('last_used_at DESC')], unique=False)
        batch_op.create_index('idx_bookmarks_name', ['name'], unique=False)
        batch_op.create_index('idx_bookmarks_pinyin', ['pinyin_initials'], unique=False)

    op.create_table('relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("type IN ('phone', 'email', 'social', 'other')", name='ck_relations_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.create_index('idx_relations_type', ['type'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), server_default=sa.text("'#6B7280'"), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('idx_tags_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('idx_tags_name')

    op.drop_table('tags')
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.drop_index('idx_relations_type')

    op.drop_table('relations')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index('idx_bookmarks_pinyin')
        batch_op.drop_index('idx_bookmarks_name')
        batch_op.drop_index('idx_bookmarks_last_used')

    op.drop_table('bookmarks')
    op.drop_table('authentication')
    # ### end Alembic commands ###
